"""The benchmark CASES of the old C++ campaign ( `nsdot/solvers_des_familles` ), for the python `sdot`.

This file declares no work ( it does not import errand ): `bench_diagram.py` and `bench_newton.py`
import it, and so can any script.

    pos, w, dim = case( "uniform2d", n = 1_000_000 )
    pos, w, dim = case( "lines_voronoi" )              # the reference file, 99 944 seeds
    pos, w, dim = case( "planes_equal" )

= The cases

  name             dim  n of the campaign   what it is
  uniform2d        2    1e6 ( diagram ), 1e5 ( Newton )   uniform in [ 0.001, 0.999 ]^2, weights 0
  lines_voronoi    2    99 944 ( the file )   5 lines, sigma = 0.005, deduplicated, weights 0
  lines_equal      2    100 000                the same cloud ( NOT deduplicated ), weights = equal areas
  uniform3d        3    1e6 ( diagram ), 1e5 ( Newton )
  planes_voronoi   3    100 000                4 planes, sigma = 0.02, weights 0
  planes_equal     3    100 000                the same cloud, weights = equal volumes ( made by the old bench itself )

The domain of all of them is the unit square / cube.

= Where the reference files are

The clouds of the lines and of the planes are TEXT FILES ( the old campaign's `2d_des_familles/cases` ):
`#` header lines, then the number of seeds, then one line per seed, `x y [z] w`. The directory is
`$SDOT_CASES_DIR`, otherwise `~/nsdot/2d_des_familles/cases` ( on `lmo` the same files are under `~/nsdot` ).

When a file is missing, the VORONOI clouds are REGENERATED by the generators below ( ports of
`gen_cases.py` / `gen_cases_3d.py`, same seed, same draws ): the 3D one is the file bit for bit; the 2D one
is the file BEFORE its deduplication ( 100 000 seeds instead of 99 944 -- the old campaign removed 56
coincident pairs from it, README § 23.7 ), so its Newton run is NOT the one of the old numbers. The
`equal` clouds can not be regenerated here: their weights are the SOLUTION of a transport problem ( L-BFGS
with pysdot for the 2D one, the old bench's own Newton for the 3D one ).

= `n`

`n = None` is the size of the case in the campaign ( the file's, or 1e6 for the uniform ones ). Another `n`
draws a fresh cloud from the generator -- for the `equal` clouds that means weights 0 ( with a warning ):
a smoke test, not a case of the campaign.
"""

import os
import warnings

import numpy

EPS = 1e-4          # the seeds of the hard clouds STRICTLY inside the domain ( as in the generators )

CASE_NAMES = ( "uniform2d", "lines_voronoi", "lines_equal", "uniform3d", "planes_voronoi", "planes_equal" )

#: name -> ( dimension, file, number of seeds of the file )
FILES = {
    "lines_voronoi":  ( 2, "lines5_n100000_s0.005_voronoi.txt", 99944 ),
    "lines_equal":    ( 2, "lines5_n100000_s0.005_equal.txt",   100000 ),
    "planes_voronoi": ( 3, "planes4_n100000_s0.02_voronoi.txt", 100000 ),
    "planes_equal":   ( 3, "planes4_n100000_s0.02_equal.txt",   100000 ),
}

#: the size of the case in the old campaign when `n = None` and there is no file
DEFAULT_N = { "uniform2d": 1_000_000, "uniform3d": 1_000_000 }


def cases_dirs():
    """where the reference files are looked for, in this order: `$SDOT_CASES_DIR`, `bench/cases/` next to this
    file ( travels with the rsync of the tree to a remote machine; git-ignored ), `~/nsdot/2d_des_familles/cases`"""
    dirs = [ os.path.join( os.path.dirname( os.path.abspath( __file__ ) ), "cases" ), "~/nsdot/2d_des_familles/cases" ]
    if os.environ.get( "SDOT_CASES_DIR" ):
        dirs.insert( 0, os.environ[ "SDOT_CASES_DIR" ] )
    return [ os.path.expanduser( d ) for d in dirs ]


def cases_dir():
    """the first of `cases_dirs()` that exists ( the first one otherwise, for the error message )"""
    dirs = cases_dirs()
    return next( ( d for d in dirs if os.path.isdir( d ) ), dirs[ 0 ] )


def dimension( name ):
    return 3 if name in ( "uniform3d", "planes_voronoi", "planes_equal" ) else 2


# -- reading ---------------------------------------------------------------------------------------

def load_cloud( path ):
    """`( positions [ n, d ], weights [ n ] )` of a reference text file: `#` lines skipped, then the
    count, then `x y [z] w` per line. The dimension is the number of columns minus one."""
    with open( path, "r" ) as f:
        while True:
            line = f.readline()
            if not line:
                raise ValueError( f"{ path }: no seed count found" )
            s = line.strip()
            if s and not s.startswith( "#" ):
                count = int( float( s ) )
                break
        data = numpy.loadtxt( f, ndmin = 2 )
    if data.shape[ 0 ] != count:
        raise ValueError( f"{ path }: the header announces { count } seeds, there are { data.shape[ 0 ] } lines" )
    return numpy.ascontiguousarray( data[ :, :-1 ] ), numpy.ascontiguousarray( data[ :, -1 ] )


def save_cloud( path, pos, w, header = () ):
    """the same format, `%.17g` ( the shortest text that reads back the same double )"""
    with open( path, "w" ) as f:
        for line in header:
            f.write( f"# { line }\n" )
        f.write( f"{ len( pos ) }\n" )
        numpy.savetxt( f, numpy.column_stack( [ pos, w ] ), fmt = "%.17g" )


# -- generating ------------------------------------------------------------------------------------

def uniform( n, dim, seed = 0, wscale = 0.0 ):
    """`n` seeds uniform in [ 0.001, 0.999 ]^dim ( the old `nuage_uniforme` ). Weights 0, or, with
    `wscale`, uniform in `[ -wscale h^2, wscale h^2 ]` with `h = n^( -1 / dim )`. ( The generator is numpy's,
    not the old `mt19937_64`: the same distribution, not the same draw. )"""
    rng = numpy.random.default_rng( seed )
    pos = rng.uniform( 0.001, 0.999, size = ( n, dim ) )
    w = numpy.zeros( n )
    if wscale != 0:
        h = n ** ( -1.0 / dim )
        w = rng.uniform( -wscale * h * h, wscale * h * h, n )
    return pos, w


def make_lines( nb_lines, rng, min_len = 0.7 ):
    """`nb_lines` chords of the unit square, each long enough to CROSS it ( `gen_cases.py` )"""
    out = []
    while len( out ) < nb_lines:
        def on_border():
            t = rng.random()
            side = rng.integers( 4 )
            return { 0: ( t, 0.0 ), 1: ( 1.0, t ), 2: ( t, 1.0 ), 3: ( 0.0, t ) }[ int( side ) ]
        a = numpy.array( on_border() )
        b = numpy.array( on_border() )
        if numpy.linalg.norm( b - a ) >= min_len:
            out.append( ( a, b ) )
    return out


def lines_cloud( n, nb_lines = 5, sigma = 0.005, seed = 0 ):
    """`n` seeds around `nb_lines` chords of the square, a gaussian transverse spread of standard
    deviation `sigma`, uniform along the line ( `gen_cases.py::make_cloud` ). Weights 0."""
    rng = numpy.random.default_rng( seed )
    lines = make_lines( nb_lines, rng )
    lens = numpy.array( [ numpy.linalg.norm( b - a ) for a, b in lines ] )
    which = rng.choice( len( lines ), size = n, p = lens / lens.sum() )
    t = rng.random( n )
    e = rng.normal( 0.0, sigma, n )
    A = numpy.array( [ a for a, b in lines ] )[ which ]
    B = numpy.array( [ b for a, b in lines ] )[ which ]
    D = B - A
    L = numpy.linalg.norm( D, axis = 1 )[ :, None ]
    N = numpy.stack( [ -D[ :, 1 ], D[ :, 0 ] ], axis = 1 ) / L
    P = A + t[ :, None ] * D + e[ :, None ] * N
    return numpy.clip( P, EPS, 1 - EPS ), numpy.zeros( n )


def make_planes( nb, rng ):
    """`nb` planes through the cube: a random unit normal, an offset so that the plane passes near the
    center ( `gen_cases_3d.py` )"""
    out = []
    while len( out ) < nb:
        u = rng.normal( size = 3 )
        u /= numpy.linalg.norm( u )
        c = u @ numpy.array( [ 0.5, 0.5, 0.5 ] ) + rng.uniform( -0.25, 0.25 )
        out.append( ( u, c ) )
    return out


def planes_cloud( n, nb_planes = 4, sigma = 0.02, seed = 0 ):
    """`n` seeds around `nb_planes` planes of the cube, gaussian transverse spread `sigma`; the position
    on the plane is drawn by REJECTION in the cube ( `gen_cases_3d.py::make_cloud` ). Weights 0."""
    rng = numpy.random.default_rng( seed )
    planes = make_planes( nb_planes, rng )
    pts = []
    per = n // len( planes ) + 1
    for u, c in planes:
        a = numpy.array( [ 1.0, 0.0, 0.0 ] )
        if abs( u[ 0 ] ) > 0.9:
            a = numpy.array( [ 0.0, 1.0, 0.0 ] )
        v1 = numpy.cross( u, a )
        v1 /= numpy.linalg.norm( v1 )
        v2 = numpy.cross( u, v1 )
        got = []
        while sum( len( g ) for g in got ) < per:
            m = 4 * per
            st = rng.uniform( -1.0, 1.0, size = ( m, 2 ) ) * 1.2
            P = c * u + st[ :, 0 ][ :, None ] * v1 + st[ :, 1 ][ :, None ] * v2
            ok = numpy.all( ( P > 0 ) & ( P < 1 ), axis = 1 )
            got.append( P[ ok ] )
        P = numpy.concatenate( got )[ :per ]
        P = P + rng.normal( 0.0, sigma, size = ( len( P ), 1 ) ) * u
        pts.append( P )
    P = numpy.concatenate( pts )
    rng.shuffle( P )
    return numpy.clip( P[ :n ], EPS, 1 - EPS ), numpy.zeros( n )


# -- the DENSITIES of the old campaign ( the target of the transport, the seeds uniform ) ---------------------------------
#
#   gauss4       § 9  ( `solver/Densite.h::densite_jeu`, 4 gaussians ): centres ( 0.26, 0.30 ), ( 0.72, 0.26 ), ( 0.34, 0.74 ),
#                ( 0.76, 0.70 ), widths `sigma x { 1, 0.7, 1.3, 1 }`, masses 0.35, 0.25, 0.25, 0.15, no floor; the domain is the
#                unit square ( `SumOfGaussians( support_box = ... )` ); n = 1e5, the width continuation sqrt( 2 ) from s = 0.5
#   image        § 12 ( `solver/Image.h::image_synthese`, the GPU campaign's image, doc/08 ): N x N pixels on the unit square,
#                a smooth background `0.1 + 0.9 ( sin 3 pi x cos 2 pi y )^2`, a sharp disk ( +3 ), a thin band ( +5 ); n = 2e4
#   image_hole   the same with an EMPTY square ( `x in ( 0.62, 0.86 ), y in ( 0.10, 0.34 )`: 5.8 % of the pixels at zero )

DENSITY_CASES = ( "gauss4", "image", "image_hole" )

#: the size of the density cases in the old campaign
DENSITY_N = { "gauss4": 100_000, "image": 20_000, "image_hole": 20_000 }


def gauss4( sigma = 0.02 ):
    """`( centres [ 4, 2 ], widths [ 4 ], masses [ 4 ] )` of the old default set ( `densite_jeu`, `nb_gauss >= 4` )"""
    centres = numpy.array( [ [ 0.26, 0.30 ], [ 0.72, 0.26 ], [ 0.34, 0.74 ], [ 0.76, 0.70 ] ] )
    return centres, sigma * numpy.array( [ 1.0, 0.7, 1.3, 1.0 ] ), numpy.array( [ 0.35, 0.25, 0.25, 0.15 ] )


def synthetic_image( size = 512, hole = True ):
    """THE OLD SYNTHETIC IMAGE ( `image_synthese` ), as `Image.values`: `[ size, size ]`, the FIRST index along x ( pixel
    `( i, j )` is `[ i, i + 1 ] x [ j, j + 1 ] / size` )"""
    c = ( numpy.arange( size ) + 0.5 ) / size
    x, y = numpy.meshgrid( c, c, indexing = "ij" )
    r = 0.10 + 0.9 * ( numpy.sin( 3 * numpy.pi * x ) * numpy.cos( 2 * numpy.pi * y ) ) ** 2
    r = r + 3.0 * ( ( x - 0.30 ) ** 2 + ( y - 0.70 ) ** 2 < 0.15 ** 2 )
    r = r + 5.0 * ( numpy.abs( x - y ) < 0.02 )
    if hole:
        r = numpy.where( ( x > 0.62 ) & ( x < 0.86 ) & ( y > 0.10 ) & ( y < 0.34 ), 0.0, r )
    return r


def density_target( name, sigma = 0.02, size = 512 ):
    """the TARGET of a density case ( an `sdot` distribution, imported here: this file declares no work )"""
    from sdot import Image, SumOfGaussians
    if name == "gauss4":
        c, s, m = gauss4( sigma )
        return SumOfGaussians( c, s, weights = m, support_box = ( [ 0.0, 0.0 ], [ 1.0, 1.0 ] ) )
    if name in ( "image", "image_hole" ):
        return Image( values = synthetic_image( size, hole = name == "image_hole" ), origin = [ 0.0, 0.0 ],
                      frame = numpy.eye( 2 ) / size )
    raise ValueError( f"unknown density case { name !r } ( { ', '.join( DENSITY_CASES ) } )" )


# -- the entry point -------------------------------------------------------------------------------

def case( name, n = None, seed = 0, wscale = 0.0 ):
    """`( positions [ n, dim ], weights [ n ], dim )` of the benchmark case `name` ( see the module
    docstring ). `wscale` only concerns the uniform cases. Raises a `FileNotFoundError` that says where
    the reference files are expected when `n = None` needs one that is not there and it can not be
    regenerated."""
    if name not in CASE_NAMES:
        raise ValueError( f"unknown case { name !r } ( { ', '.join( CASE_NAMES ) } )" )
    dim = dimension( name )

    if name.startswith( "uniform" ):
        return ( *uniform( DEFAULT_N[ name ] if n is None else int( n ), dim, seed, wscale ), dim )

    d, fname, n_file = FILES[ name ]
    path = os.path.join( cases_dir(), fname )
    if n is None or int( n ) == n_file:
        if os.path.exists( path ):
            pos, w = load_cloud( path )
            return pos, w, dim
        if name.endswith( "_equal" ):
            raise FileNotFoundError(
                f"case { name !r }: the reference file { fname } is not in { cases_dir() } "
                "( the directory is $SDOT_CASES_DIR, by default ~/nsdot/2d_des_familles/cases; on lmo ~/nsdot/2d_des_familles/cases ). "
                "The equal-mass weights are the SOLUTION of a transport problem, so they can not be regenerated here "
                "( `case( ..., n = <another n> )` gives the same cloud with weights 0 for a smoke run )" )
        n = 100000                       # the generators draw the cloud BEFORE its deduplication
        warnings.warn( f"case { name !r }: { path } not found -- regenerated with n = { n } "
                       + ( "( the old file has 99944 seeds after its deduplication: not the old Newton case )" if d == 2 else "( identical to the file )" ) )
    elif name.endswith( "_equal" ):
        warnings.warn( f"case { name !r } at n = { n } != { n_file }: weights 0 ( the equal-mass weights only exist for the file ): a smoke run, not the case" )

    n = int( n )
    pos, w = lines_cloud( n, 5, 0.005, seed ) if d == 2 else planes_cloud( n, 4, 0.02, seed )
    return pos, w, dim


if __name__ == "__main__":
    import sys
    for nm in ( sys.argv[ 1: ] or CASE_NAMES ):
        try:
            p, w, d = case( nm )
            print( f"{ nm :16s} dim { d }  n = { len( p ) }  weights in [ { w.min() :.3g }, { w.max() :.3g } ]  positions in [ { p.min() :.3g }, { p.max() :.4g } ]" )
        except FileNotFoundError as e:
            print( f"{ nm :16s} { e }" )
