// THE CARD'S LINEAR SOLVER ON THE SYSTEMS OF A NEWTON SOLVE, REPLAYED ( `calibration_lmo_today.md`, GPU step 5 ): the systems
// that `bench_newton --lin-dump=<prefix>` wrote ( `Linear2D.cuh::dump_system` ), solved in sequence by one `CardLinear` as
// the Newton solve does ( recycling, hierarchies ), the minimum of `reps` runs, iterations and time per system, the true
// relative residual and a checksum of the solutions ( two runs must print the same ). A compile takes ~10 s, not the minutes
// of the whole Newton call: what the solver's variants were measured with.
//
//   nvcc -std=c++20 -arch=sm_75 -O3 --expt-relaxed-constexpr --extended-lambda -I<sdot-ffi>/include -I<loom>/include //        -o linbench linbench.cu
//   ./linbench <prefix> <first> <count> [float=1] [sa=1] [nu=1] [kcycle=2] [lanes=4] [reps=3] [check=1] ...
//
// ( the options are `LinOptions`'s, see `main`; `nsys profile --cuda-graph-trace=node` sees the kernels of the graphs )
namespace sdot { template<class... A> int kernel_form( A &&... ); }   // generated by loom; unused here
#include <sdot/gpu/Linear2D.cuh>
#include <cstdio>
#include <cstring>
#include <map>
#include <string>
#include <vector>

using namespace sdot;
using namespace sdot::gpu2d;
using TC = std::uint32_t;

struct Pool {
    std::vector<void *> ptrs;
    template<class T> struct View {
        T *p;
        struct D { T *raw; };
        D data() const { return { p }; }
    };
    template<class T> View<T> view( SI n ) {
        void *p = nullptr;
        if ( cudaMalloc( &p, sizeof( T ) * n ) != cudaSuccess ) p = nullptr;
        ptrs.push_back( p );
        return { static_cast<T *>( p ) };
    }
    ~Pool() { for ( void *p : ptrs ) cudaFree( p ); }
};

struct System {
    SI n = 0, nnz = 0;
    std::vector<SI> row;
    std::vector<TC> col;
    std::vector<double> val, dia, b;
    bool load( const std::string &name ) {
        FILE *f = std::fopen( name.c_str(), "rb" );
        if ( ! f ) return false;
        SI head[ 3 ];
        if ( std::fread( head, sizeof( SI ), 3, f ) != 3 || head[ 2 ] != 4 ) { std::fclose( f ); return false; }
        n = head[ 0 ]; nnz = head[ 1 ];
        row.resize( n + 1 ); col.resize( nnz ); val.resize( nnz ); dia.resize( n ); b.resize( n );
        bool ok = std::fread( row.data(), sizeof( SI ), n + 1, f ) == size_t( n + 1 ) && std::fread( col.data(), 4, nnz, f ) == size_t( nnz )
               && std::fread( val.data(), 8, nnz, f ) == size_t( nnz ) && std::fread( dia.data(), 8, n, f ) == size_t( n )
               && std::fread( b.data(), 8, n, f ) == size_t( n );
        std::fclose( f );
        return ok;
    }
    double relres( const std::vector<double> &d ) const {
        double rr = 0, bb = 0;
        for ( SI i = 0; i < n; ++i ) {
            double s = dia[ i ] * d[ i ];
            for ( SI e = row[ i ]; e < row[ i + 1 ]; ++e ) s -= val[ e ] * d[ col[ e ] ];
            rr += ( b[ i ] - s ) * ( b[ i ] - s );
            bb += b[ i ] * b[ i ];
        }
        return std::sqrt( rr / bb );
    }
};

__global__ void spin( double *x, int n ) {
    double v = threadIdx.x;
    for ( int k = 0; k < n; ++k ) v = v * 0.999999 + 1e-9;
    if ( v == 12345 ) x[ 0 ] = v;
}

/// the clocks of the card up before anything is timed
static void warm_up() {
    double *x;
    cudaMalloc( &x, 8 );
    const double t0 = wall_now();
    while ( wall_now() - t0 < 0.5 ) { spin<<<272, 128>>>( x, 20000 ); cudaDeviceSynchronize(); }
    cudaFree( x );
}

template<class TV>
int run( std::vector<System> &sys, const LinOptions &lo, int reps, bool check ) {
    SI n = sys[ 0 ].n, nnz_cap = 0;
    for ( auto &s : sys ) nnz_cap = std::max( nnz_cap, s.nnz );
    cudaStream_t stream;
    cudaStreamCreate( &stream );
    CudaQueue queue( stream );
    Pool data;
    SI *row = data.view<SI>( n + 1 ).p;
    TC *col = data.view<TC>( nnz_cap ).p;
    double *val = data.view<double>( nnz_cap ).p, *dia = data.view<double>( n ).p, *b = data.view<double>( n ).p, *d = data.view<double>( n ).p;
    std::vector<double> best_t( sys.size(), 1e30 ), hd( n );
    std::vector<int> its( sys.size() );
    std::vector<double> res( sys.size() );
    double best_total = 1e30;
    std::uint64_t checksum = 0;
    for ( int rep = 0; rep < reps; ++rep ) {
        Pool pool;
        CardLinear<TC,TV> lin;
        if ( ! lin.prepare( pool, n, nnz_cap, lo ) ) { std::printf( "prepare failed\n" ); return 1; }
        double total = 0;
        for ( size_t k = 0; k < sys.size(); ++k ) {
            System &s = sys[ k ];
            cudaMemcpy( row, s.row.data(), sizeof( SI ) * ( n + 1 ), cudaMemcpyHostToDevice );
            cudaMemcpy( col, s.col.data(), sizeof( TC ) * s.nnz, cudaMemcpyHostToDevice );
            cudaMemcpy( val, s.val.data(), sizeof( double ) * s.nnz, cudaMemcpyHostToDevice );
            cudaMemcpy( dia, s.dia.data(), sizeof( double ) * n, cudaMemcpyHostToDevice );
            cudaMemcpy( b, s.b.data(), sizeof( double ) * n, cudaMemcpyHostToDevice );
            cudaDeviceSynchronize();
            const int it0 = lin.st.nb_iter;
            const double t0 = wall_now();
            const bool ok = lin.solve( queue, pool, CsrView<TC>{ n, row, col, val, dia }, b, d );
            cudaStreamSynchronize( stream );
            const double t = wall_now() - t0;
            total += t;
            best_t[ k ] = std::min( best_t[ k ], t );
            its[ k ] = lin.st.nb_iter - it0;
            if ( ! ok ) std::printf( "  system %zu: FAILED\n", k );
            if ( check && rep == 0 ) {
                cudaMemcpy( hd.data(), d, sizeof( double ) * n, cudaMemcpyDeviceToHost );
                res[ k ] = s.relres( hd );
                std::uint64_t hsh = 1469598103934665603ull;
                for ( double v : hd ) { std::uint64_t u; std::memcpy( &u, &v, 8 ); hsh = ( hsh ^ u ) * 1099511628211ull; }
                checksum ^= hsh + k;
            }
        }
        cuda_check( cudaGetLastError(), "run" );
        best_total = std::min( best_total, total );
        if ( rep == 0 ) {
            std::printf( "  hierarchies %d, levels %zu, t_hierarchy %.4f s:", lin.st.nb_hierarchies, lin.lev.size(), lin.st.t_hierarchy );
            for ( auto &L : lin.lev ) {
                SI nz = 0;
                if ( L.A.row ) cudaMemcpy( &nz, L.A.row + L.A.n, sizeof( SI ), cudaMemcpyDeviceToHost );
                std::printf( " %lld(%.1f)", L.A.n, double( nz ) / L.A.n );
            }
            std::printf( "\n" );
        }
    }
    int it_tot = 0;
    for ( size_t k = 0; k < sys.size(); ++k ) {
        it_tot += its[ k ];
        std::printf( "  sys %2zu  n %8lld  nnz %9lld  it %4d  %8.3f ms  %6.3f ms/it  relres %.2e\n", k, sys[ k ].n, sys[ k ].nnz, its[ k ], 1e3 * best_t[ k ],
                     1e3 * best_t[ k ] / std::max( its[ k ], 1 ), check ? res[ k ] : 0.0 );
    }
    std::printf( "  checksum %016llx\n", ( unsigned long long ) checksum );
    double sum_best = 0;
    for ( double t : best_t ) sum_best += t;
    std::printf( "TOTAL it %d ( %.1f / solve )  t_lin %.4f s ( sum of per-system minima %.4f )  %.3f ms/it\n", it_tot, double( it_tot ) / sys.size(), best_total, sum_best,
                 1e3 * sum_best / std::max( it_tot, 1 ) );
    return 0;
}

int main( int argc, char **argv ) {
    if ( argc < 4 ) { std::printf( "usage: linbench prefix first count [key=value...]\n" ); return 1; }
    std::string prefix = argv[ 1 ];
    int first = std::atoi( argv[ 2 ] ), count = std::atoi( argv[ 3 ] );
    std::map<std::string,double> kv;
    for ( int a = 4; a < argc; ++a ) {
        const char *eq = std::strchr( argv[ a ], '=' );
        if ( eq ) kv[ std::string( argv[ a ], size_t( eq - argv[ a ] ) ) ] = std::atof( eq + 1 );
    }
    auto get = [&]( const char *k, double dflt ) { auto it = kv.find( k ); return it == kv.end() ? dflt : it->second; };
    LinOptions lo;
    lo.method = int( get( "method", lo.method ) );
    lo.tol = get( "tol", lo.tol );
    lo.shift = int( get( "shift", lo.shift ) );
    lo.nu = int( get( "nu", lo.nu ) );
    lo.cheb = get( "cheb", lo.cheb );
    lo.recycle = int( get( "recycle", lo.recycle ) );
    lo.rebuild = int( get( "rebuild", lo.rebuild ) );
    lo.stop = int( get( "stop", lo.stop ) );
    lo.kcycle = int( get( "kcycle", lo.kcycle ) );
    lo.trace = get( "trace", 0 ) != 0;
    lo.nu0 = int( get( "nu0", lo.nu0 ) );
    lo.smoothed = int( get( "sa", lo.smoothed ) );
    lo.omega = get( "omega", lo.omega );
    lo.truncate = get( "truncate", lo.truncate );
    lo.kfrom = int( get( "kfrom", lo.kfrom ) );
    lo.plain_warp = int( get( "pw", lo.plain_warp ) );
    lo.lanes = int( get( "lanes", lo.lanes ) );
    const int reps = int( get( "reps", 3 ) );
    const bool check = get( "check", 1 ) != 0;
    std::vector<System> sys;
    for ( int k = first; k < first + count; ++k ) {
        System s;
        if ( ! s.load( prefix + "_" + std::to_string( k ) + ".bin" ) ) { std::printf( "cannot load %d\n", k ); return 1; }
        sys.push_back( std::move( s ) );
    }
    std::printf( "%s %d..%d: n %lld\n", prefix.c_str(), first, first + count - 1, sys[ 0 ].n );
    warm_up();
    return get( "float", 0 ) != 0 ? run<float>( sys, lo, reps, check ) : run<double>( sys, lo, reps, check );
}
